---
# The GPII framework tests on Fedora require that Orca has been set up.

- name: Check to see if the Orca user directory exists
  stat:
    path: "{{ gpii_framework_user_home_dir }}/.local/share/orca"
  register: gpii_framework_orca_dir_result

- name: Create Orca user directory if required
  file:
    path: "{{ gpii_framework_user_home_dir }}/.local/share/orca"
    state: directory
    mode: 0755
    owner: "{{ gpii_framework_username }}"
    group: "{{ gpii_framework_groupname }}"
  when: gpii_framework_orca_dir_result.stat.exists == false
    
- name: Create Orca configuration file
  copy:
    src: orca-user-settings.conf
    dest: "{{ gpii_framework_user_home_dir }}/.local/share/orca/user-settings.conf"
    owner: "{{ gpii_framework_username }}"
    group: "{{ gpii_framework_groupname }}"
  when: gpii_framework_orca_dir_result.stat.exists == false

- name: Enable and start PackageKit
  service:
    name: packagekit
    enabled: true
    state: started
